### ISSUE TITLE
There are a few roaming asterisks in the introduction page

### ISSUE THREAD

**Issue by gumpgourou** [digitalearthafrica/deafrica-training-workshop#10]
![image](https://user-images.githubusercontent.com/32540651/89358759-8daeaf80-d707-11ea-965a-07716fa5654d.png)

**Comment by eefaye** [comment]
That's weird! It renders correctly in the `.ipynb` file in the sandbox.
![image](https://user-images.githubusercontent.com/45861242/89359009-25ac9900-d708-11ea-979d-5603bb620d73.png)

**Comment by eefaye** [comment]
As per Caitlin's comment on PR #8 this is probably due to spacing in the HTML. This has been rectified - an extra line break has been added before the dot points start.
