### ISSUE TITLE
Feedback from Tessa

### ISSUE THREAD

**Issue by andrewdhicks** [digitalearthafrica/deafrica-training-workshop#23]
- [x] Use of in-text links instead of ‘here’
       I think I only saw this once or twice but for example when you say, **‘you can sign in here’** I’d make it **‘you can sign into the Sandbox’** and hyperlink **‘sign into the Sandbox’**

- [ ] Can you make external links open in a new window? They currently take users away from the site

**Comment by eefaye** [comment]
Session 1 content has been checked to make sure there are no 'here'-hyperlinks. 

I cannot get external links to open in a new tab or window, someone with more HTML expertise will probably be able to. 
I have tried the following formats:

- `<a href="http://example.com/" target="_blank">Hello, world!</a>`
- `[link](url){:target="_blank"}`
- `[Google] (http://www.google.com){target="_blank"}`
